#!/bin/sh
# embed-agent.sh — generate src/agent_src.h from BP/GIT.AGENT.
# Copyright (C) 2026 Gordon Heydon.  GPL-2.0-only (see LICENSE).
#
# The drivers carry the agent's source compiled into the binary: they must be
# able to seed an account where NOTHING is installed, which is exactly the case
# where the shipped BASIC is not there to read.
#
# THIS EXISTS AS ITS OWN SCRIPT because it was inline in build-gitd.sh, which
# only the UniVerse build runs.  build-udt.sh never regenerated the header, so
# udt-git embedded whatever happened to be in the tree — a copy predating the
# per-platform transport seam, with every $IFDEF already resolved to the
# UniVerse branch.  It seeded a UniVerse agent into a UniData account, which
# then failed to compile on TIMEOUT/READBLK: statements UniData does not have.
# One generator, called by both builds, is the only way these cannot drift.
set -e
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SRC="$HERE/src"
AGENT="$HERE/BP/GIT.AGENT"
OUT="$SRC/agent_src.h"

[ -f "$AGENT" ] || { echo "embed-agent: no $AGENT" >&2; exit 1; }

{
    echo "/* Generated by embed-agent.sh from BP/GIT.AGENT — do not edit. */"
    echo "#ifndef AGENT_SRC_H"
    echo "#define AGENT_SRC_H"
    echo "static const char GIT_AGENT_SRC[] ="
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/"/' -e 's/$/\\n"/' "$AGENT"
    echo ";"
    echo "#endif"
} > "$OUT"

# The seam is the whole reason this must be current: an embedded agent with no
# $IFDEF in it has already been flattened to one platform.
n=$(grep -c '\$IFDEF' "$AGENT" || true)
echo "embedded BP/GIT.AGENT -> $(basename "$OUT") ($(wc -l < "$AGENT") lines, $n \$IFDEF)"
