* MVX — a native compiler and runtime for Pick/MultiValue BASIC.
* Copyright (C) 2026 Gordon Heydon.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License, version 2, as
* published by the Free Software Foundation.  There is NO WARRANTY, to
* the extent permitted by law; see the LICENSE file for details.
*
* SPDX-License-Identifier: GPL-2.0-only
* /**
*  * @file GIT.INIT
*  * @version 4.0
*  */
SUBROUTINE GIT.INIT
$IFDEF MVX
OUT = ""
CALL GITINIT(".git", OUT)
PRINT OUT
$ELSE
DIM AV(8) ; MAT AV = ""            ;* argument vector for GIT.OBJ
REPO = @PATH : "/.git"
AV(1) = REPO
CALL GIT.OBJ("INIT", MAT AV, 1, OBJOUT)
CALL GIT.ECHO(OBJOUT)
$ENDIF
RETURN